### ISSUE TITLE
調查可用的金融相關 API

### ISSUE THREAD

**Issue by EvanLo62** [ByteEat8Bits/DevOps-Final-Project#2]

**Comment by Weixun93** [comment]
1. FinMind API(資料包含技術面、基本面、籌碼面和消息面等，還可以進行回測、繪製K線圖及儀錶板)
link: https://finmindtrade.com/analysis/#/data/api
2. yfinance(Yahoo 可用)
link: https://ithelp.ithome.com.tw/articles/10341344
link: https://www.cs.nccu.edu.tw/~sichiu/11102_ppt/11102_week_14.pdf
3. 臺灣證券交易所OpenAPI
link: https://openapi.twse.com.tw/
link: https://vocus.cc/article/667ebabbfd897800016b3086
link: https://hackmd.io/@aaronlife/python-ex-stock-by-api?utm_source=preview-mode&utm_medium=rec (可顯示在網頁，教學)

**Comment by Weixun93** [comment]
241112, 14:02
¶ yfinance 功能較多，但是會是受限於 Yahoo 官方網站的連線限制，雖然讀取次數有每日上限，但目前專案來說非常足夠。
¶ FinMind, openapi.twse 功能較偏向台灣股市，美股只有金額以及上市檔數。
若要以功能性來看，**_yfinance_**較適合
